// src-tauri/src/license/watermark.rs
//
// 试用过期水印文本。仅在 LicenseState::TrialExpired 时由调用方注入到导出文件中。
// 文案按编译期 Cargo feature 选语言：
//   lang-zh → "本文件由 Dimkey 试用版生成 · https://dimkey.app"
//   lang-en → "Generated by Dimkey trial · https://dimkey.app"

pub const WATERMARK_ZH: &str = "本文件由 Dimkey 试用版生成 · https://dimkey.app";
pub const WATERMARK_EN: &str = "Generated by Dimkey trial · https://dimkey.app";

/// 返回当前编译语言对应的水印文本。
pub fn watermark_text() -> &'static str {
    #[cfg(feature = "lang-en")]
    {
        WATERMARK_EN
    }
    #[cfg(all(feature = "lang-zh", not(feature = "lang-en")))]
    {
        WATERMARK_ZH
    }
    #[cfg(not(any(feature = "lang-zh", feature = "lang-en")))]
    {
        WATERMARK_ZH
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn watermark_contains_dimkey_url() {
        let txt = watermark_text();
        assert!(txt.contains("dimkey.app"));
    }

    #[test]
    fn watermark_text_non_empty() {
        assert!(!watermark_text().is_empty());
    }

    #[cfg(feature = "lang-zh")]
    #[test]
    fn lang_zh_text_contains_chinese() {
        assert!(WATERMARK_ZH.contains("试用版"));
    }

    #[cfg(feature = "lang-en")]
    #[test]
    fn lang_en_text_is_english() {
        assert!(WATERMARK_EN.contains("trial"));
        assert!(!WATERMARK_EN.contains("试用"));
    }
}
